# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/codecov/all/codecov.rbi
#
# codecov-0.2.15

module Codecov
end
class SimpleCov::Formatter::Codecov
  def black(str); end
  def build_params(ci); end
  def create_report(report); end
  def detect_ci; end
  def display_header; end
  def file_network; end
  def file_to_codecov(file); end
  def format(result, disable_net_blockers = nil); end
  def green(str); end
  def gzip_report(report); end
  def handle_report_response(report); end
  def net_blockers(switch); end
  def red(str); end
  def result_to_codecov(result); end
  def result_to_codecov_coverage(result); end
  def result_to_codecov_messages(result); end
  def result_to_codecov_report(result); end
  def retry_request(req, https); end
  def shortened_filename(file); end
  def upload_to_codecov(ci, report); end
  def upload_to_v2(url, report, query, query_without_token); end
  def upload_to_v4(url, report, query, query_without_token); end
end
