# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `simplecov-cobertura` gem.
# Please instead update this file by running `bin/tapioca gem simplecov-cobertura`.


# pkg:gem/simplecov-cobertura#lib/simplecov-cobertura/version.rb:1
module SimpleCov; end

# pkg:gem/simplecov-cobertura#lib/simplecov-cobertura/version.rb:2
module SimpleCov::Formatter; end

# pkg:gem/simplecov-cobertura#lib/simplecov-cobertura/version.rb:3
class SimpleCov::Formatter::CoberturaFormatter
  # pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:15
  def initialize(result_file_name: T.unsafe(nil)); end

  # pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:19
  def format(result); end

  private

  # pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:153
  def build_branches_by_line(file, branches_by_line); end

  # pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:170
  def condition_start_line(condition); end

  # pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:189
  def extract_rate(percent); end

  # Roughly mirrors private method SimpleCov::Formatter::HTMLFormatter#output_coverage
  #
  # pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:178
  def output_message(result, output_path); end

  # pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:193
  def project_root; end

  # pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:185
  def resolve_filename(filename); end

  # pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:37
  def result_to_xml(result); end

  # pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:140
  def set_branch_attributes(line, file_line, branches_by_line); end

  # pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:121
  def set_class_attributes(class_, file); end

  # pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:92
  def set_coverage_attributes(coverage, result); end

  # pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:135
  def set_line_attributes(line, file_line); end

  # pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:109
  def set_package_attributes(package, name, result); end
end

# pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:13
SimpleCov::Formatter::CoberturaFormatter::DTD_URL = T.let(T.unsafe(nil), String)

# pkg:gem/simplecov-cobertura#lib/simplecov-cobertura.rb:12
SimpleCov::Formatter::CoberturaFormatter::RESULT_FILE_NAME = T.let(T.unsafe(nil), String)

# pkg:gem/simplecov-cobertura#lib/simplecov-cobertura/version.rb:4
SimpleCov::Formatter::CoberturaFormatter::VERSION = T.let(T.unsafe(nil), String)
