---
inherit_mode:
  merge:
    - Exclude
    - Include

plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  Include:
    - "sorbet/rbi/shims/**/*.rbi"
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/ClassStructure:
  Enabled: true
# Cannot add type annotations to forwarded blocks
Naming/BlockForwarding:
  Enabled: false
Naming/FileName:
  Exclude:
    - lib/yard-sorbet.rb
Sorbet/ForbidTUntyped:
  Enabled: true
Sorbet/StrictSigil:
  Enabled: true
